/* Nicolas Ramirez
Functions in golang
*/

package main

import "fmt"

//fUNCTIONS ARE LIKE SMALL ENCHANTMENTS IN THE BIGGER MAGIC THAT IS A PROGRAM 
//FUNCTIONS ALLOWS US TO REUSE CODE WHILE VARIATING INPUTS AND OUTPUTS DEPENDING ON WHAT WE NEED


func Lyrics(){ //DECLARATION OF A FUNCTION
	fmt.Printf(" Sasageyo"); //CODE TO BE EXECUTED
} //END OF FUNCTION


func main(){
	fmt.Println("Sasageyo") 
	Lyrics(); //THIS IS THE WAY THAT WE WILL CALL A FUNCTION INSIDE ANOTHER WHEN WE HAVE ALREADY DECLARED IT BEFORE
}
